### ISSUE TITLE
comparison to related packages

### ISSUE THREAD

**Issue by timotheecour** [alehander42/zero-functional#21]
https://github.com/petermora/nimLazy seems quite related; would be nice to compare against it

**Comment by michael72** [comment]
... well maybe the focus is different - both library's intention is to provide functional programming to nim.
the focus in zero-functional is to provide fp without the runtime penalty that usually comes when using fp. nimLazy has a different approach and relies heavily on closure iterators see [Nim Manual](https://nim-lang.org/docs/manual.html#iterators-and-the-for-statement-first-class-iterators)

We already had some discussion about naming conventions and what functions to implement in 
#11 - also with references to other fp libaries (in nim and other languages) - the difficulty is finding the right naming for all supported functions that yield the same results.

So - a comparison to other libraries would be nice, but what do you want to compare? Names, conventions, ...?
